### PR TITLE
feat: create signup form for fourth step

### PR DESCRIPTION
**Pull request by fedasevich**
## Describe your changes

- Added "Password" and "Confirm password" input fields
- Implemented hide/show password functionality
- Set password validation for a minimum of 8 characters
- Display error message for invalid password length
- Disabled Complete button until both fields are filled
image
image
image

## Issue ticket code (and/or) and link

- [Link to JIRA ticket](https://homecareaid.atlassian.net/browse/AC-7?atlOrigin=eyJpIjoiOTQzYTdmYmJjNTM3NDg3MGEyZWNmZTcxMTdlYzM4NjgiLCJwIjoiaiJ9)

### **General**

- [x] Assigned myself to the PR
- [x] Assigned the appropriate labels to the PR
- [x] Assigned the appropriate reviewers to the PR
- [ ] Updated the documentation
- [x] Performed a self-review of my code
- [x] Types for input and output parameters
- [x] Don't have "any" on my code
- [ ] Used the try/catch pattern for error handling
- [x] Don't have magic numbers
- [x] Compare only with constants not with strings
- [x] No ternary operator inside the ternary operator
- [x] Don't have commented code
- [x] no links in the code, env links should be in env file (for example: server url), constant links (for example default avatar URL) should be in constant file.
- [x] Used camelCase for variables and functions
- [ ] Date and time formats are on the constants
- [ ] Functions are public only if it's used outside the class
- [x] No hardcoded values
- [ ] covered by tests
- [x] Check your commit messages meet the [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/).

### Frontend

- [x] Components and business logic are separated
- [x] Colors, Font Size, and Font Name is on the theme or in the constants
- [x] No text in the components, use i18n approach
- [x] No inline styles
- [x] Imports are absolute
- [x] Attach a screenshot if PR has visual changes.

### Backend

- [ ] Swagger documentation updated
- [ ] Database requests are optimized and not redundant
- [ ] Unit tests written
- [ ] use ConfigService instead of process.env
- [ ] use transactions if there is a call chain that mutates data in different tables
- [ ] use @index decorator for frequently requested data

### CODE REVIEW

**Comment by lyudad** [comment]
Screenshot 2023-11-10 at 12 29 43
Screenshot 2023-11-10 at 12 30 05

**Comment by fedasevich** [comment]
Regular material ui input also doesn't have any spacing from the value:
image
Also according to figma design we also don't have spacing there:
image

What do you recommend to do about that? Should i add a few px spacing there?

**Comment by lyudad** [comment]
> Regular material ui input also doesn't have any spacing from the value: image Also according to figma design we also don't have spacing there: image
> 
> What do you recommend to do about that? Should i add a few px spacing there?

checked. agree. I prefer 2nd option https://mui.com/material-ui/react-text-field/, with space

**Comment by fedasevich** [comment]
Changed input:
image
image
image

**Review by lyudad — APPROVED** [review]

**Pull request merged**
